name: agroconnect_day1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  snippet_coder_utils: ^1.0.14
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/pashu.png
  - assets/images/agroconnect_text.png
  - assets/images/(Upload your agricultural identity card in pdf format).png
  - assets/images/Add the following (Optional)_ Subject, address, phone number..png
